### PR TITLE
Code formatting config + github workflow for PR

### PR DESCRIPTION
**Pull request by ncoquelet**
Hello
Here is a code formatting configuration with Prettier and EditorConfig.

* The configuration generally follows the current formatting
* I added a command in the package.json to reformat everything with `pnpm prettier:format`
* Specific files are ignored in `.prettierignore`
* Finally, I added a GitHub workflow to check the formatting in PRs (pull requests).

### CODE REVIEW

**Comment by ncoquelet** [comment]
Hum... the check should be failed !

**Comment by ncoquelet** [comment]
:ok_hand:

**Comment by haouarihk** [comment]
nice work

**Comment by haouarihk** [comment]
tho it should only be triggered by pull requests
the push is uneeded.
since you can validate locally

this is only for review

**Comment by ncoquelet** [comment]
> tho it should only be triggered by pull requests the push is uneeded. since you can validate locally

fully agreed with you, it's a mistake
thanks for review

**Pull request merged**
